[project]
name = "nordstern"
version = "0.1.0"
description = "Battlefield drone navigation using phased array AoA, IMU, and RF signal events"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "scipy>=1.15.3",
]
